---

- name: agrega repositorio docker configurado en las variables
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  become: yes
 
- name: agrega repositorio docker configurado en las variables
  command: dnf install docker-ce-20.10.6-3.el8 -y
  become: yes
  
- name: Enable docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Execute cat 
  shell:
    cmd: |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
      EOF
  become: yes  
  
- name: install packages kube
  dnf:
    name: "{{ item }}"
    disable_excludes: kubernetes
    state: latest
  become: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
  become: yes
