---

- name: Mostrar lista de discos
  debug:
      var: hostvars[inventory_hostname].ansible_devices.keys() | list

- name: identifica el primer disco libre y lo almacena en la variable disk
  set_fact:
    disks: "/dev/{{ item.key }}"
  when:
    # si el disco no está particionado tendrá libre 
    # estas variables de los facts
    - not item.value.partitions
    - not item.value.holders
    - not item.value.links.uuids
    - not item.value.links.labels
    # los discos serán /dev/vd? o /dev/sd? filtramos el
    # resto de resultados
    - item.key | regex_search ("vd|sd")
  with_dict: "{{ ansible_devices }}"

- name: mostrar el resultado del disco libre
  debug: 
    msg: "Disco vacio {{ disks }}"

- name: Crea el volumen group 
  lvg:
    vg: data_vg
    pvs: "{{ disks }}"
    state: present

- name: Crea un volumen logico con todo el espacio disponible
  lvol:
    vg: data_vg
    lv: nfs_lv
    size: 100%FREE

- name: Crea un xfs filesystem on data_vg
  filesystem:
    fstype: xfs
    dev: /dev/data_vg/nfs_lv

- name: Create a directory if it does not exist
  file:
    path: /srv/nfs
    state: directory
    mode: '0755'

- name: agrega linea en fstab
  command: echo "/dev/data_vg/nfs_lv        /srv/nfs                xfs     defaults        0 0" >> /etc/fstab
  become: yes

- name: Mountamos el sistema de ficheros nfs
  mount:
    path: /srv/nfs
    src: /dev/data_vg/nfs_lv
    state: mounted
    fstype: xfs
