---

- name: Configuramos el firewall para acceder a los servicios de kubernetes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  become: yes
  with_items:
    - "{{ firewall_ports }}"

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Configuramos kudeadm
  ansible.builtin.shell: kubeadm config images pull
  
- name: Permitir el acceso de los workers
  firewalld:
    rich_rule: rule family=ipv4 source address="{{ item }}" accept
    permanent: yes
    state: enabled
  become: yes
  with_items:
    - "{{ ipworkers }}"

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Permitir el acceso de los contenedores
  firewalld:
    rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
    zone: public
    permanent: yes
    state: enabled
  become: yes

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Iniciamos kudeadm
  command: kubeadm init --pod-network-cidr 10.1.0.0/16
  become: yes

- name: Obtenemos token
  command: kubeadm token create --print-join-command
  become: yes
  register: join_token

- name: Almacenamos la respuesta en un archivo
  copy:
    dest: "/tmp/token1"
    content: |
      {{ join_token.stdout }}

- name: Specifying a destination path
  fetch:
    src: "/tmp/token1"
    dest: "/tmp/token1"
    flat: yes

