---

- name: enable services
  systemd:
    name: firewalld
    state: started
    enabled: yes
    masked: no
  become: yes
    
- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
  become: yes

- name: Activar transparent masquerading
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: update settings net.bridge.bridge-nf-call-ip6tables
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  
- name: update settings net.bridge.bridge-nf-call-iptables
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
    
- name: desactivas swap 
  become: yes 
  shell: swapoff  -a

- name: Elimina una linea del archivo fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    regexp: '^%cs-swap' 
    # Usamos state absent para eliminar la linea
    state: absent
    backup: no

